import { mkdir, readdir, watch } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "@mdx-js/mdx";
import matter from "gray-matter";
import rehypeSlug from "rehype-slug";
import remarkGfm from "remark-gfm";
import { z } from "zod";
import { type SitePath, sitePaths, type TocEntry } from "../src/site/types";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const contentDir = join(rootDir, "content");
const generatedDir = join(rootDir, "src", "generated");
const generatedMdxDir = join(generatedDir, "mdx");
const watchMode = process.argv.includes("--watch");

const MDX_PROVIDER_IMPORT = "../../site/mdx-components";

function assertMdxCompiledOutput(compiled: string, fileBase: string): void {
	if (compiled.includes("site/ui")) {
		throw new Error(
			`[build-mdx-content] ${fileBase}.mdx: compiled output references "../../site/ui". ` +
				`Expected provider import from ${MDX_PROVIDER_IMPORT}. Check @mdx-js/mdx version or compile options.`,
		);
	}
	if (!compiled.includes(MDX_PROVIDER_IMPORT)) {
		throw new Error(
			`[build-mdx-content] ${fileBase}.mdx: compiled output missing mdx-components provider import.`,
		);
	}
}

const frontmatterSchema = z.object({
	path: z.enum(sitePaths),
	title: z.string().min(1),
	description: z.string().min(1),
});

function slugify(text: string): string {
	return text
		.toLowerCase()
		.replace(/[^a-z0-9\s-]/g, "")
		.trim()
		.replace(/\s/g, "-");
}

function extractToc(content: string): TocEntry[] {
	const entries: TocEntry[] = [];
	const headingRe = /^(#{2})\s+(.+)$/gm;
	let match = headingRe.exec(content);

	while (match !== null) {
		const depth = 2;
		const label = match[2].trim();
		const id = slugify(label);
		entries.push({ id, label, depth });
		match = headingRe.exec(content);
	}

	return entries;
}

async function discoverMdxFiles(): Promise<string[]> {
	const entries = await readdir(contentDir, { withFileTypes: true });
	const files = entries
		.filter((e) => e.isFile() && e.name.endsWith(".mdx"))
		.map((e) => e.name.replace(/\.mdx$/, ""));
	const indexPages = files.filter((name) => name === "index");
	const nonIndexPages = files
		.filter((name) => name !== "index")
		.sort((left, right) => left.localeCompare(right));
	return [...indexPages, ...nonIndexPages];
}

async function build(): Promise<void> {
	await mkdir(generatedDir, { recursive: true });
	await mkdir(generatedMdxDir, { recursive: true });

	const mdxBases = await discoverMdxFiles();
	const pages: Array<{
		path: SitePath;
		title: string;
		description: string;
		fileBase: string;
		toc: TocEntry[];
	}> = [];

	for (const base of mdxBases) {
		const filePath = join(contentDir, `${base}.mdx`);
		const rawSource = await Bun.file(filePath).text();
		const parsed = matter(rawSource);
		const frontmatter = frontmatterSchema.parse(parsed.data);
		const toc = extractToc(parsed.content);

		const compiled = await compile(parsed.content, {
			jsxImportSource: "react",
			providerImportSource: MDX_PROVIDER_IMPORT,
			remarkPlugins: [remarkGfm],
			rehypePlugins: [rehypeSlug],
		});
		const compiledText = String(compiled);

		assertMdxCompiledOutput(compiledText, base);

		const outputPath = join(generatedMdxDir, `${base}.tsx`);
		await Bun.write(
			outputPath,
			`// @ts-nocheck\n/* eslint-disable */\n/* auto-generated by scripts/build-mdx-content.ts */\n${compiledText}`,
		);

		pages.push({
			path: frontmatter.path,
			title: frontmatter.title,
			description: frontmatter.description,
			fileBase: base,
			toc,
		});
	}

	const pageEntries = pages.map(
		(p) => `	${JSON.stringify(p.path)}: {
		path: ${JSON.stringify(p.path)},
		title: ${JSON.stringify(p.title)},
		description: ${JSON.stringify(p.description)},
		loadComponent: () => import("./mdx/${p.fileBase}"),
		toc: ${JSON.stringify(p.toc, null, 2)},
	}`,
	);

	const contentFile = `/* auto-generated by scripts/build-mdx-content.ts */
import type { SitePage, SitePath } from "../site/types";

export const sitePages = ${JSON.stringify(
		pages.map((p) => ({ path: p.path, title: p.title })),
		null,
		2,
	)} satisfies ReadonlyArray<Pick<SitePage, "path" | "title">>;

const pagesMap = {
${pageEntries.join(",\n")}
} satisfies Record<SitePath, SitePage>;

export function getPage(path: SitePath): SitePage | undefined {
	return pagesMap[path];
}
`;

	await Bun.write(join(generatedDir, "content.ts"), contentFile);
	console.log(
		`built ${pages.length} page(s): ${pages.map((p) => p.path).join(", ")}`,
	);
}

async function watchAndBuild(): Promise<void> {
	await build();
	console.log("watching content/**/*.mdx");

	let timeout: ReturnType<typeof setTimeout> | null = null;

	for await (const _event of watch(contentDir, { recursive: true })) {
		if (timeout) {
			clearTimeout(timeout);
		}

		timeout = setTimeout(() => {
			void build().catch((error) => {
				console.error(error);
			});
		}, 80);
	}
}

if (watchMode) {
	await watchAndBuild();
} else {
	await build();
}
