// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).

import type { Query, DatabasePropertyType } from "@haustle/notion-orm";
import { DatabaseClient } from "@haustle/notion-orm";
import { z } from "zod";

// Database client factory
export const CustomerOrders = (auth: string) => {
    return new DatabaseClient<DatabaseSchemaType, ColumnNameToColumnType>({
        id,
        camelPropertyNameToNameAndTypeMap: columnNameToColumnProperties,
        schema,
        name: "Customer Orders",
        auth
    });
};

// Identity (Notion data source id)
const id = "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4";

// Row types (TypeScript)
export type DatabaseSchemaType = {
    orderName: string;
    notes?: string;
    total?: number;
    orderDate?: {
        start: string;
        end?: string;
    };
    paid?: boolean;
    customerEmail?: string;
    customerPhone?: string;
    receiptUrl?: string;
};

// Column metadata
const columnNameToColumnProperties = {
    "orderName": {
        columnName: "Order Name",
        type: "title"
    },
    "notes": {
        columnName: "Notes",
        type: "rich_text"
    },
    "total": {
        columnName: "Total",
        type: "number"
    },
    "orderDate": {
        columnName: "Order Date",
        type: "date"
    },
    "paid": {
        columnName: "Paid",
        type: "checkbox"
    },
    "customerEmail": {
        columnName: "Customer Email",
        type: "email"
    },
    "customerPhone": {
        columnName: "Customer Phone",
        type: "phone_number"
    },
    "receiptUrl": {
        columnName: "Receipt URL",
        type: "url"
    }
} as const satisfies Record<keyof DatabaseSchemaType, {
    columnName: string;
    type: DatabasePropertyType;
}>;

// Derived column types (for query filters/sorts)
type ColumnNameToColumnType = {
    [Property in keyof typeof columnNameToColumnProperties]: (typeof columnNameToColumnProperties)[Property]["type"];
};

// Typed database query arguments
export type QuerySchemaType = Query<DatabaseSchemaType, ColumnNameToColumnType>;

// Runtime validation (Zod)
export const schema = z.object({
    orderName: z.string(),
    notes: z.string().nullable().optional(),
    total: z.number().nullable().optional(),
    orderDate: z.object({
        start: z.string(),
        end: z.string().nullable().optional()
    }).nullable().optional(),
    paid: z.boolean().optional(),
    customerEmail: z.string().nullable().optional(),
    customerPhone: z.string().nullable().optional(),
    receiptUrl: z.string().nullable().optional()
});
