// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).

import type { DatabaseColumns, DatabaseDefinition, InferDatabaseSchema, Query } from "@haustle/notion-orm";
import { DatabaseClient } from "@haustle/notion-orm";

// Column metadata
const columns = {
    "orderName": {
        columnName: "Order Name",
        type: "title"
    },
    "notes": {
        columnName: "Notes",
        type: "rich_text"
    },
    "total": {
        columnName: "Total",
        type: "number"
    },
    "orderDate": {
        columnName: "Order Date",
        type: "date"
    },
    "paid": {
        columnName: "Paid",
        type: "checkbox"
    },
    "customerEmail": {
        columnName: "Customer Email",
        type: "email"
    },
    "customerPhone": {
        columnName: "Customer Phone",
        type: "phone_number"
    },
    "receiptUrl": {
        columnName: "Receipt URL",
        type: "url"
    }
} as const satisfies DatabaseColumns;

// Row types (TypeScript)
export type DatabaseSchemaType = InferDatabaseSchema<typeof columns>;
// Typed database query arguments
export type QuerySchemaType = Query<DatabaseDefinition<typeof columns>>;
// Database client factory
export const CustomerOrders = (auth: string) => {
    return new DatabaseClient<DatabaseDefinition<typeof columns>>({
        id: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4",
        columns: columns,
        name: "Customer Orders",
        auth
    });
};
