"use strict";
// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).
Object.defineProperty(exports, "__esModule", { value: true });
exports.schema = exports.EdgeCases = void 0;
const notion_orm_1 = require("@haustle/notion-orm");
const zod_1 = require("zod");
// Database client factory
const EdgeCases = (auth) => {
    return new notion_orm_1.DatabaseClient({
        id,
        camelPropertyNameToNameAndTypeMap: columnNameToColumnProperties,
        schema: exports.schema,
        name: "Edge Cases",
        auth
    });
};
exports.EdgeCases = EdgeCases;
// Identity (Notion data source id)
const id = "c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6";
// Column metadata
const columnNameToColumnProperties = {
    "name": {
        columnName: "Name",
        type: "title"
    },
    "attachments": {
        columnName: "Attachments",
        type: "files"
    },
    "assignees": {
        columnName: "Assignees",
        type: "people"
    },
    "relatedItems": {
        columnName: "Related Items",
        type: "relation"
    },
    "createdBy": {
        columnName: "Created By",
        type: "created_by"
    },
    "lastEditedBy": {
        columnName: "Last Edited By",
        type: "last_edited_by"
    },
    "createdAt": {
        columnName: "Created At",
        type: "created_time"
    },
    "updatedAt": {
        columnName: "Updated At",
        type: "last_edited_time"
    }
};
// Runtime validation (Zod)
exports.schema = zod_1.z.object({
    name: zod_1.z.string(),
    attachments: zod_1.z.array(zod_1.z.object({
        name: zod_1.z.string(),
        url: zod_1.z.string()
    })).nullable().optional(),
    assignees: zod_1.z.array(zod_1.z.string()).nullable().optional(),
    relatedItems: zod_1.z.array(zod_1.z.string()).nullable().optional(),
    createdBy: zod_1.z.string().nullable().optional(),
    lastEditedBy: zod_1.z.string().nullable().optional(),
    createdAt: zod_1.z.string().nullable().optional(),
    updatedAt: zod_1.z.string().nullable().optional()
});
