// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).

import type { Query, DatabasePropertyType } from "@haustle/notion-orm";
import { DatabaseClient } from "@haustle/notion-orm";
import { z } from "zod";

// Database client factory
export const EdgeCases = (auth: string) => {
    return new DatabaseClient<DatabaseSchemaType, ColumnNameToColumnType>({
        id,
        camelPropertyNameToNameAndTypeMap: columnNameToColumnProperties,
        schema,
        name: "Edge Cases",
        auth
    });
};

// Identity (Notion data source id)
const id = "c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6";

// Row types (TypeScript)
export type DatabaseSchemaType = {
    name: string;
    attachments?: {
        name: string;
        url: string;
    }[];
    assignees?: string[];
    relatedItems?: string[];
    createdBy?: string;
    lastEditedBy?: string;
    createdAt?: string;
    updatedAt?: string;
};

// Column metadata
const columnNameToColumnProperties = {
    "name": {
        columnName: "Name",
        type: "title"
    },
    "attachments": {
        columnName: "Attachments",
        type: "files"
    },
    "assignees": {
        columnName: "Assignees",
        type: "people"
    },
    "relatedItems": {
        columnName: "Related Items",
        type: "relation"
    },
    "createdBy": {
        columnName: "Created By",
        type: "created_by"
    },
    "lastEditedBy": {
        columnName: "Last Edited By",
        type: "last_edited_by"
    },
    "createdAt": {
        columnName: "Created At",
        type: "created_time"
    },
    "updatedAt": {
        columnName: "Updated At",
        type: "last_edited_time"
    }
} as const satisfies Record<keyof DatabaseSchemaType, {
    columnName: string;
    type: DatabasePropertyType;
}>;

// Derived column types (for query filters/sorts)
type ColumnNameToColumnType = {
    [Property in keyof typeof columnNameToColumnProperties]: (typeof columnNameToColumnProperties)[Property]["type"];
};

// Typed database query arguments
export type QuerySchemaType = Query<DatabaseSchemaType, ColumnNameToColumnType>;

// Runtime validation (Zod)
export const schema = z.object({
    name: z.string(),
    attachments: z.array(z.object({
        name: z.string(),
        url: z.string()
    })).nullable().optional(),
    assignees: z.array(z.string()).nullable().optional(),
    relatedItems: z.array(z.string()).nullable().optional(),
    createdBy: z.string().nullable().optional(),
    lastEditedBy: z.string().nullable().optional(),
    createdAt: z.string().nullable().optional(),
    updatedAt: z.string().nullable().optional()
});
