// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).

import type { Query, DatabasePropertyType } from "@haustle/notion-orm";
import { DatabaseClient } from "@haustle/notion-orm";
import { z } from "zod";

// Database client factory
export const InventoryItems = (auth: string) => {
    return new DatabaseClient<DatabaseSchemaType, ColumnNameToColumnType>({
        id,
        camelPropertyNameToNameAndTypeMap: columnNameToColumnProperties,
        schema,
        name: "Inventory Items",
        auth
    });
};

// Identity (Notion data source id)
const id = "b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5";

// Option literals for select/status/multi_select columns
export const CategoryPropertyValues = [
    "Electronics",
    "Clothing",
    "Food"
] as const;

export const AvailabilityPropertyValues = [
    "In Stock",
    "Out of Stock",
    "Backordered"
] as const;

export const TagsPropertyValues = [
    "New",
    "Sale",
    "Featured"
] as const;

// Row types (TypeScript)
export type DatabaseSchemaType = {
    itemName: string;
    category?: (typeof CategoryPropertyValues)[number] | (string & {});
    availability?: (typeof AvailabilityPropertyValues)[number] | (string & {});
    tags?: ((typeof TagsPropertyValues)[number] | (string & {}))[];
    sku?: string;
    price?: number;
};

// Column metadata
const columnNameToColumnProperties = {
    "itemName": {
        columnName: "Item Name",
        type: "title"
    },
    "category": {
        columnName: "Category",
        type: "select"
    },
    "availability": {
        columnName: "Availability",
        type: "status"
    },
    "tags": {
        columnName: "Tags",
        type: "multi_select"
    },
    "sku": {
        columnName: "SKU",
        type: "unique_id"
    },
    "price": {
        columnName: "Price",
        type: "number"
    }
} as const satisfies Record<keyof DatabaseSchemaType, {
    columnName: string;
    type: DatabasePropertyType;
}>;

// Derived column types (for query filters/sorts)
type ColumnNameToColumnType = {
    [Property in keyof typeof columnNameToColumnProperties]: (typeof columnNameToColumnProperties)[Property]["type"];
};

// Typed database query arguments
export type QuerySchemaType = Query<DatabaseSchemaType, ColumnNameToColumnType>;

// Runtime validation (Zod)
export const schema = z.object({
    itemName: z.string(),
    category: z.enum(CategoryPropertyValues).nullable().optional(),
    availability: z.enum(AvailabilityPropertyValues).nullable().optional(),
    tags: z.array(z.enum(TagsPropertyValues)).nullable().optional(),
    sku: z.string().nullable().optional(),
    price: z.number().nullable().optional()
});
