"use strict";
// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).
Object.defineProperty(exports, "__esModule", { value: true });
exports.schema = exports.TagsPropertyValues = exports.AvailabilityPropertyValues = exports.CategoryPropertyValues = exports.InventoryItems = void 0;
const notion_orm_1 = require("@haustle/notion-orm");
const zod_1 = require("zod");
// Database client factory
const InventoryItems = (auth) => {
    return new notion_orm_1.DatabaseClient({
        id,
        camelPropertyNameToNameAndTypeMap: columnNameToColumnProperties,
        schema: exports.schema,
        name: "Inventory Items",
        auth
    });
};
exports.InventoryItems = InventoryItems;
// Identity (Notion data source id)
const id = "b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5";
// Option literals for select/status/multi_select columns
exports.CategoryPropertyValues = [
    "Electronics",
    "Clothing",
    "Food"
];
exports.AvailabilityPropertyValues = [
    "In Stock",
    "Out of Stock",
    "Backordered"
];
exports.TagsPropertyValues = [
    "New",
    "Sale",
    "Featured"
];
// Column metadata
const columnNameToColumnProperties = {
    "itemName": {
        columnName: "Item Name",
        type: "title"
    },
    "category": {
        columnName: "Category",
        type: "select"
    },
    "availability": {
        columnName: "Availability",
        type: "status"
    },
    "tags": {
        columnName: "Tags",
        type: "multi_select"
    },
    "sku": {
        columnName: "SKU",
        type: "unique_id"
    },
    "price": {
        columnName: "Price",
        type: "number"
    }
};
// Runtime validation (Zod)
exports.schema = zod_1.z.object({
    itemName: zod_1.z.string(),
    category: zod_1.z.enum(exports.CategoryPropertyValues).nullable().optional(),
    availability: zod_1.z.enum(exports.AvailabilityPropertyValues).nullable().optional(),
    tags: zod_1.z.array(zod_1.z.enum(exports.TagsPropertyValues)).nullable().optional(),
    sku: zod_1.z.string().nullable().optional(),
    price: zod_1.z.number().nullable().optional()
});
